### ISSUE TITLE
Suggestion: Use md5 hashing to detect duplicate files 

### ISSUE THREAD

**Issue by ghost** [Volafile/volafile-bugs#82]
If you hash every file, you can compare new uploads to files currently on the server.
From there you could either discard the upload and warn the user the file currently exists in that room, or you could create a download link as usual and discard one of the files while linking both download links to that one file.

Could be a useful way to avoid spam and duplicate files while saving space on the servers.

EDIT: Of course md5 is just a suggestion, that hashing algorithm isn't the important part here

**Comment by laino** [comment]
Then there's the problem of the download servers file storage timeouts (automatic removal) being independent from the rest of Volafile (so that file servers will still delete the file even if the rest of Vola is down).

Building this would mean I'd have to signal the file servers to reset the removal timeout on the relevant file, and this could lead to some annoying race conditions.

**Comment by laino** [comment]
Since we need to receive the whole file anyways to calculate the md5 sum, and since a shortage of storage space is never a problem for Volafile, I'll close this.
